[project]
name = "time-release-safe"
authors = ["Hammed <hamsohood@gmail.com>"]
description = "A decentralized time-release safe with inheritance and penalty features"
telemetry = true
requirements = []
license = "MIT"

[contracts.time-release-safe]
path = "contracts/time-release-safe.clar"

[contracts.beneficiary-safe]
path = "contracts/beneficiary-safe.clar"

[contracts.multi-beneficiary-safe]
path = "contracts/multi-beneficiary-safe.clar"
